language: c
sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - pkg-config
      - libbsd-dev

install:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka-dev_1.0.1-2_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka0_1.0.1-2_amd64.deb
  - wget http://mirrors.edge.kernel.org/ubuntu/pool/main/p/pkg-config/pkg-config_0.29.1-0ubuntu2_amd64.deb
  - sha256sum libcmocka-dev_1.0.1-2_amd64.deb | grep -q edb0dcfa14893b0a03375c4fe3b852043ce8fca8f2397cde340562554f6d50eb
  - sha256sum libcmocka0_1.0.1-2_amd64.deb | grep -q 797155b45a8288a860c4ed9dd3f161420f09ebf362de30166d9f6b98bfc27dd0
  - sudo dpkg -i libcmocka0_1.0.1-2_amd64.deb
  - sudo dpkg -i libcmocka-dev_1.0.1-2_amd64.deb
  - sudo dpkg -i pkg-config_0.29.1-0ubuntu2_amd64.deb

script:
  - ./build.sh
  - make check
