* Release 0.1
** DONE README.md
   - State "DONE"       from "TODO"       [2018-02-21 Wed 12:12]
   - Note taken on [2018-02-17 Sat 11:02] \\
     Write a proper README.md for the github folks.
** DONE MAN page
   - Note taken on [2018-03-23 Fri 16:40] \\
     Ignored. the header file has been documented instead.
   - Note taken on [2018-02-17 Sat 11:02] \\
     For everyone else, write a proper manpage explaining the API
** DONE Fudge dice
   - Note taken on [2018-03-23 Fri 17:56] \\
     Done.
   - Note taken on [2018-02-17 Sat 11:02] \\
     The syntax should be XdF and the results should be [-1, -1, 0, 0, +1, +1].
** DONE verify dual licencing with Lews Van Winkle
   - Note taken on [2018-03-23 Fri 15:48] \\
     No direct reply to my mail, but he starred github repo.
   - Note taken on [2018-02-17 Sat 11:30] \\
     Verify that dual licencing has been done properly by consult
     Lewis Van Winkle the author of tinyexpr.
** TODO Remove dependency on libbsd
   - Note taken on [2018-02-17 Sat 11:05] \\
     arc4random_uniform() should be moved into the source. On BSD we just use
     the library function.
